# -*- coding: utf-8 -*-
"""Image recoginition .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Qef2iPUdptaQO7LdvMyGUjHf7A7_sV6
"""

# ==========================================
# Basic Image Recognition using AI Library
# Pre-trained Model: MobileNetV2
# ==========================================

# Install libraries (Run once if needed)
# pip install tensorflow pillow matplotlib

from tensorflow.keras.applications.mobilenet_v2 import (
    MobileNetV2,
    preprocess_input,
    decode_predictions
)

from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt

# ------------------------------------------
# Step 1: Load Pre-trained AI Model
# ------------------------------------------

model = MobileNetV2(weights='imagenet')

# ------------------------------------------
# Step 2: Load Image
# ------------------------------------------

img_path = "cat.avif"   # Put your image name here

img = image.load_img(img_path, target_size=(224, 224))

# Display Image
plt.imshow(img)
plt.axis("off")
plt.show()

# ------------------------------------------
# Step 3: Convert Image to Array
# ------------------------------------------

img_array = image.img_to_array(img)

# Add extra dimension
img_array = np.expand_dims(img_array, axis=0)

# Preprocess image
img_array = preprocess_input(img_array)

# ------------------------------------------
# Step 4: Perform Recognition
# ------------------------------------------

predictions = model.predict(img_array)

# Decode output
results = decode_predictions(predictions, top=3)[0]

# ------------------------------------------
# Step 5: Display Results
# ------------------------------------------

print("\n===== Recognition Results =====\n")

for i, result in enumerate(results):
    print(f"{i+1}. {result[1]}  --> Confidence: {result[2]*100:.2f}%")